# Generated by Django 3.0.3 on 2020-05-20 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_info',
            name='user',
        ),
    ]
